### ISSUE TITLE
R-CMD-check-build workflow: remove vignettes from the check step?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Workflows#34]
s. the discussion https://github.com/Open-Systems-Pharmacology/Workflows/pull/33#pullrequestreview-2191397067

**Comment by Yuri05** [comment]
e.g. these steps (taken from the raw build log of [this ospsuite-R workflow tun](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/actions/runs/10141825445/job/28039879719))

![grafik](https://github.com/user-attachments/assets/26eff98e-2a9f-4f5f-8da6-cc6b946ebac2)
![grafik](https://github.com/user-attachments/assets/eb155132-befe-412e-9bfd-24348da7ae32)

could be omitted, because the vignettes were already built before:

![grafik](https://github.com/user-attachments/assets/49b59d71-836d-4a7e-9bad-95466a0b51ce)

@Felixmil

**Comment by Felixmil** [comment]
This can be closes following #40

**Comment by Yuri05** [comment]
Fixed by https://github.com/Open-Systems-Pharmacology/Workflows/pull/40
